// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znanrfrtlsldrdmveptr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuYW5yZnJ0bHNsZHJkbXZlcHRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NTQyMjEsImV4cCI6MjA3MTIzMDIyMX0.fbGTMeCK2jaMAiTHhPWEW9IOrT6luFhRVHGW0H7jKn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});